export interface ChatSession {
  id: string;
  title: string;
  messages: ChatMessage[];
  createdAt: number;
  updatedAt: number;
}

export interface AIProfile {
  id: string;
  name: string;
  personality: string;
  behavioralPatterns?: string;
  goals?: string;
  coreValues?: string;
  likes?: string;
  dislikes?: string;
  speakingStyle?: string;
  backstory: string;
  appearance: string;
  scenario?: string;
  referenceImage: string | null;
  voiceURI?: string | null;
  voicePitch?: number;
  voiceSpeed?: number;
  autoReadMessages?: boolean;
  voiceDescription?: string;
  voiceProvider?: 'browser' | 'elevenlabs' | 'gemini';
  geminiTtsVoice?: string;       // Gemini TTS voice name e.g. "Kore", "Aoede"
  geminiTtsModel?: string;       // Gemini TTS model ID
  geminiTtsStyle?: string;       // Natural language style prompt for Gemini TTS
  asyncVoiceId?: string | null;
  responseLength: 'short' | 'medium' | 'long' | 'custom';
  responseDetail: 'low' | 'medium' | 'high' | 'standard';
  responseTone: 'friendly' | 'formal' | 'humorous' | 'serious';
  customParagraphCount: number | null;
  customWordCount: number | null;
  // Environmental awareness (replaces old proactive + ambient frequency fields)
  environmentalAwarenessEnabled?: boolean;
  envStillnessMinutes?: number;       // minutes of stillness before a check-in (default 20)
  envMovementResponse?: boolean;      // react when movement is detected after stillness
  envSoundResponse?: boolean;         // react to significant sound changes
  envLightResponse?: boolean;         // react to significant light changes
  envMinGapMinutes?: number;          // minimum minutes between any AI-initiated messages (default 30)
  // Legacy — kept so old saved personas load without errors
  proactiveMessageFrequency?: 'off' | '1h' | '6h' | '12h' | '24h' | 'low' | 'medium' | 'high';
  aiCanGenerateSpeech?: boolean;
  textOnlyMode?: boolean;  // When true: no *actions* or roleplay emotes — clean text for TTS
  elevenLabsModelId?: string; // ElevenLabs model to use for TTS
  elStability?: number;      // ElevenLabs voice stability (0-1)
  elSimilarity?: number;     // ElevenLabs similarity boost (0-1)
  elStyle?: number;          // ElevenLabs style exaggeration (0-1)
  elSpeakerBoost?: boolean;  // ElevenLabs speaker boost
  elSpeakingRate?: number;   // ElevenLabs speaking rate (0.7-1.2)
  dynamicEmotion?: boolean;  // Auto-detect emotion from AI reply and adjust voice
  knowsItsAI: boolean;
  model: string;
  llmProvider?: 'claude' | 'gemini';
  temperature: number;
  maxTokens?: number;
  timeAwareness: boolean;
  ambientMode: boolean;
  ambientFrequency: 'off' | '1h' | '6h' | '12h' | '24h' | 'low' | 'medium' | 'high';
  aiCanGenerateImages: boolean;
  imageStyle?: string;
  imageGenerationInstructions?: string[];
  // Legacy Google fields (kept so old exported personas still load correctly)
  aiCanUseWebSearch?: boolean;
  aiCanUseWeather?: boolean;
  aiCanUseCalendar?: boolean;
  aiCanUseYouTube?: boolean;
  aiCanUseGoogleMaps?: boolean;
  googleToolsEnabled?: boolean;   // Master toggle: run Gemini web search even when Claude is active
  aiCanUseMotion?: boolean;        // Share device motion/orientation context with the AI
  aiCanSendProactiveEmails?: boolean;
  aiCanBrowse?: boolean;
  aiCanUseTools?: boolean;
  // Removed: aiCanUseGmail, aiCanUseBlogger
  chatHistory?: ChatMessage[];
  sessions?: ChatSession[];
  activeSessionId?: string;
  memories?: Memory[];
  journal?: JournalEntry[];
  lastProactiveStatus?: string;
}

export interface UserProfile {
  name: string;
  email: string;
  info: string;
  preferences: string;
  appearance: string;
  referenceImage: string | null;
  locationOverride?: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  content: string;
  timestamp: number;
  attachments?: { type: 'image' | 'text' | 'pdf'; content: string; name: string }[];
  read?: boolean;
  groundingUrls?: { title: string; url: string }[];
  rating?: 'up' | 'down' | number;
  feedbackComment?: string;
}

export interface KnowledgeBaseDocument {
  name: string;
  content: string;
  personaId?: string;  // which persona this document belongs to (undefined = shared/legacy)
}

export interface Memory {
  id: string;
  content: string;
  strength: number; // 1–10
  timestamp: number;
  lastAccessed: number;
  isImportant: boolean;
}

export interface JournalEntry {
  id: string;
  date: string; // ISO string
  content: string;
  isAutoGenerated: boolean;
}

export interface GalleryItem {
  id: string;
  type: 'uploaded' | 'generated';
  mediaType?: 'image' | 'video';
  url: string;
  prompt?: string;
  timestamp: number;
  personaId?: string; // which persona this image belongs to (undefined = unassigned)
}

export interface ProactiveCommunication {
  id: string;
  type: 'message' | 'email' | 'blog';
  title: string;
  content: string;
  timestamp: number;
}
